wip

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,18 +1,133 @@
-FROM axisecp/acap-native-sdk:latest-aarch64-ubuntu24.04
+ARG ARCH=aarch64
+ARG REPO=axisecp
+ARG SDK=acap-native-sdk
+ARG UBUNTU_VERSION=24.04
+ARG VERSION=12.2.0
 
-# Install additional development tools
-RUN apt-get update && apt-get install -y \
+FROM ${REPO}/${SDK}:${VERSION}-${ARCH}-ubuntu${UBUNTU_VERSION}
+
+# Set general arguments
+ARG ARCH
+ARG SDK_LIB_PATH_BASE=/opt/axis/acapsdk/sysroots/${ARCH}/usr
+ARG BUILD_DIR=/opt/build
+
+#-------------------------------------------------------------------------------
+# Prepare build environment
+#-------------------------------------------------------------------------------
+
+# Install build dependencies for cross compiling OpenCV and development tools
+RUN DEBIAN_FRONTEND=noninteractive \
+    apt-get update && apt-get install -y -f --no-install-recommends \
+    cmake \
+    build-essential \
     git \
     curl \
     wget \
-    build-essential \
-    cmake \
     gdb \
-    sudo \
-    && rm -rf /var/lib/apt/lists/*
+    pkg-config \
+    autoconf \
+    automake \
+    libtool \
+    autotools-dev \
+    && apt-get clean && \
+    rm -rf /var/lib/apt/lists/*
 
-# Set the working directory
+# Build and install libmodbus for aarch64
+WORKDIR ${BUILD_DIR}
+RUN git clone https://github.com/stephane/libmodbus.git && \
+    cd libmodbus && \
+    git checkout v3.1.10 && \
+    ./autogen.sh && \
+    . /opt/axis/acapsdk/environment-setup* && \
+    ./configure --host=aarch64-linux-gnu --prefix=/opt/axis/acapsdk/sysroots/${ARCH}/usr && \
+    make -j "$(nproc)" && \
+    make install
+
+#-------------------------------------------------------------------------------
+# Build OpenCV libraries
+#-------------------------------------------------------------------------------
+
+ARG OPENCV_VERSION=4.10.0
+ARG OPENCV_DIR=${BUILD_DIR}/opencv
+ARG OPENCV_SRC_DIR=${OPENCV_DIR}/opencv-${OPENCV_VERSION}
+ARG OPENCV_BUILD_DIR=${OPENCV_DIR}/build
+
+WORKDIR ${OPENCV_DIR}
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN curl -fsSL https://github.com/opencv/opencv/archive/$OPENCV_VERSION.tar.gz | tar -xz
+
+WORKDIR ${OPENCV_BUILD_DIR}
+ENV COMMON_CMAKE_FLAGS="-S $OPENCV_SRC_DIR \
+        -B $OPENCV_BUILD_DIR \
+        -D CMAKE_INSTALL_PREFIX=$SDK_LIB_PATH_BASE \
+        -D CMAKE_BUILD_TYPE=RELEASE \
+        -D WITH_OPENEXR=OFF \
+        -D WITH_GTK=OFF \
+        -D WITH_V4L=OFF \
+        -D WITH_FFMPEG=OFF \
+        -D WITH_GSTREAMER=OFF \
+        -D WITH_GSTREAMER_0_10=OFF \
+        -D BUILD_LIST=core,imgproc,video \
+        -D BUILD_EXAMPLES=OFF \
+        -D BUILD_OPENCV_APPS=OFF \
+        -D BUILD_DOCS=OFF \
+        -D BUILD_JPEG=ON \
+        -D BUILD_PNG=OFF \
+        -D WITH_JASPER=OFF \
+        -D BUILD_PROTOBUF=OFF \
+        -D OPENCV_GENERATE_PKGCONFIG=ON "
+
+# hadolint ignore=SC2086
+RUN if [ "$ARCH" = armv7hf ]; then \
+        # Source SDK environment to get cross compilation tools
+        . /opt/axis/acapsdk/environment-setup* && \
+        # Configure build with CMake
+        cmake \
+        -D CMAKE_CXX_COMPILER=${CXX%-g++*}-g++ \
+        -D CMAKE_CXX_FLAGS="${CXX#*-g++}" \
+        -D CMAKE_C_COMPILER=${CC%-gcc*}-gcc \
+        -D CMAKE_C_FLAGS="${CC#*-gcc}" \
+        -D CMAKE_TOOLCHAIN_FILE=${OPENCV_SRC_DIR}/platforms/linux/arm-gnueabi.toolchain.cmake \
+        -D CPU_BASELINE=NEON,VFPV3 \
+        -D ENABLE_NEON=ON \
+        -D ENABLE_VFPV3=ON \
+        $COMMON_CMAKE_FLAGS && \
+        # Build and install OpenCV
+        make -j "$(nproc)" install ; \
+    elif [ "$ARCH" = aarch64 ]; then \
+        # Source SDK environment to get cross compilation tools
+        . /opt/axis/acapsdk/environment-setup* && \
+        # Configure build with CMake
+        # No need to set NEON and VFP for aarch64 since they are implicitly
+        # present in an any standard armv8-a implementation.
+        cmake \
+        -D CMAKE_CXX_COMPILER=${CXX%-g++*}-g++ \
+        -D CMAKE_CXX_FLAGS="${CXX#*-g++}" \
+        -D CMAKE_C_COMPILER=${CC%-gcc*}-gcc \
+        -D CMAKE_C_FLAGS="${CC#*-gcc}" \
+        -D CMAKE_TOOLCHAIN_FILE=${OPENCV_SRC_DIR}/platforms/linux/aarch64-gnu.toolchain.cmake \
+        $COMMON_CMAKE_FLAGS && \
+        # Build and install OpenCV
+        make -j "$(nproc)" install ; \
+    else \
+        printf "Error: '%s' is not a valid value for the ARCH variable\n" "$ARCH"; \
+        exit 1; \
+    fi
+
+#-------------------------------------------------------------------------------
+# Copy the built library files to application directory
+#-------------------------------------------------------------------------------
+
+WORKDIR /opt/app
+COPY ./app .
+RUN mkdir lib && \
+    cp -P ${OPENCV_BUILD_DIR}/lib/lib*.so* ./lib/
+
+#-------------------------------------------------------------------------------
+# Finally build the ACAP application
+#-------------------------------------------------------------------------------
+
+RUN . /opt/axis/acapsdk/environment-setup*
+
+# Set the working directory for development
 WORKDIR /workspace
-
-# Ensure root is the default user
-USER root 
